### PR TITLE
Don't force use of deprecated API

### PR DESCRIPTION
**Pull request by matozoid**
The latest ANTLR deprecates ...Parser.tokenNames. It is used in this project like so:

image

This PR changes that to use the suggested replacement instead: 

image

Part of this change comes from https://github.com/kshchepanovskyi/antlr4-jetbrains-adapter/commit/48c4702725916bb0c8c84fdf0cdadae032651b2b

This breaks the API, but it is pretty obvious for a user how to fix it, in my opinion.

### CODE REVIEW

**Comment by ziscloud** [comment]
please review and merge this.

**Comment by parrt** [comment]
Ok, will this break the intellij plugin for antlr? Could you tweak that one too?

**Comment by ziscloud** [comment]
no, it does not break the plugin even with the latest antlr, but it is a positive fixing of this project anyway.

**Comment by parrt** [comment]
thanks!

**Comment by matozoid** [comment]
And thanks!

**Comment by oovm** [comment]
image

Why is my `VOCABULARY` not an array?

(antlr 4.12.0)

**Comment by bjansen** [comment]
@oovm the PR has been merged but the change has not been released yet, so in antlr4-intellij-adaptor you still have to use something like:
```java
PSIElementTypeFactory.defineLanguageIElementTypes(
		ANTLRv4Language.INSTANCE,
		ANTLRv4Lexer.tokenNames,
		ANTLRv4Parser.ruleNames
);
```

**Pull request merged**
