### PR TITLE
Move to a Gradle build

### PR DESCRIPTION
**Pull request by bjansen**
I converted the project to Gradle. It will automatically download the IntelliJ SDK and build the jar. I also configured to build to publish the jar in Maven repositories.

I was able to install the artifact in my local Maven repo, then import it in `intellij-plugin-v4` to use that library instead of the current source files in `org.antlr.intellij.adaptor`. I'll provide a separate PR when/if this library ends up in a public repo.

I still need to make a few tweaks to the build to be able to publish to Central though. 
@parrt how do you usually publish stuff to Central? Using the Sonatype OSS repo?

### CODE REVIEW

**Comment by bjansen** [comment]
I also configured a Travis CI build to make sure the libray works in various versions of the IntelliJ SDK.

https://travis-ci.org/bjansen/jetbrains

**Comment by parrt** [comment]
thanks! added you as collaborator with write.

**Comment by bjansen** [comment]
Great! How do you usually deploy artifacts to Central? I'd like to improve the build to publish the jar automatically.

**Comment by parrt** [comment]
I follow procedure I doc'd for antlr: https://github.com/antlr/antlr4/blob/master/doc/releasing-antlr.md

**Pull request merged**
